 

- [专栏目录首页：【专栏必读】王道考研408操作系统+Linux系统编程万字笔记、题目题型总结、注意事项、目录导航和思维导图](https://zhangxing-tech.blog.csdn.net/article/details/121004242)

### 文章目录

- - [（1）进程终止时的三种情况](#1_5)
  - [（2）退出进程的方法](#2_40)
  - - [A：正常退出-exit和return的区别](#Aexitreturn_41)
    - [B：异常退出](#B_80)
    - [C：\_exit\(\)函数](#C_exit_83)
  - [（3）实践](#3_107)

## （1）进程终止时的三种情况

一个进程结束了，无外乎是以下三种情况中的一种

- 代码跑完，结果正确
- 代码跑完，结果不正确
- 代码没有跑完，进程被强制中断

那么一个进程结束时，操作系统是如何判断这个进程是正常结束还是非正常结束的呢？其实是通过进程的退出码，这一点可以联想到为什么C/C++中main函数最后写的是`return 0`？**因为0代表进程正常退出，非0代表进程异常退出**，在引文中其实提到了可以用`echo $?`查看上一个进程退出时的状态码

所以如果你的main函数如果返回值设置为`return 123`,那么`echo $?`的结果就是123

```c
#include <stdio.h>
int main()
{
            
            
	printf("Hello World\n");
	return 123;
}
```

![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210314222337227.png&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)  
如下，我们故意犯一个错误，那就是分母为0，但是咋们main函数的返回值是0，然后运行编译后的程序，命令提示了一个错误“浮点异常”，并且再用`echo $?`查看返回的状态码是136，是非0，这表明程序在执行到这一个语句的时候，操作系统发现异常，然后强制让进程终止。

```c
#include <stdio.h>
int main()
{
            
            
	int x=1/0;//很明显的非法操作
	return 0;
}
```

![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210314223105439.png%3Fx-oss-process%3Dimage%2Fwatermark%2Ctype_ZmFuZ3poZW5naGVpdGk%2Cshadow_10%2Ctext_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM5MTgzMDM0%2Csize_16%2Ccolor_FFFFFF%2Ct_70&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)

- 上面这就是一个强制退出的情况。其实这个过程实则是操作系统发现异常，通过kill发送信号给进程，然后让其终止的  
  ![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210314223612896.gif&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)

## （2）退出进程的方法

### A：正常退出-exit和return的区别

exit\(int status\)是一个函数，在程序任意位置使用它，进程将会终止。所以下面这段程序并没有输出文字，且进程的退出码是12，而不是0

```c
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

void test()
{
            
            
	exit(12);//进程在这里将被终止
}
int main()
{
            
            
	test();
	printf("程序执行到了这里\n");
	return 0;
}
```

![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210315093608594.png%3Fx-oss-process%3Dimage%2Fwatermark%2Ctype_ZmFuZ3poZW5naGVpdGk%2Cshadow_10%2Ctext_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM5MTgzMDM0%2Csize_16%2Ccolor_FFFFFF%2Ct_70&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)  
如果将上面`test()`函数中的`exit()`改为`return 12`，那么`return 12`代表的就是这个函数的返回值，由于函数正常执行，所以在`main`函数中文字被打印，且`echo $?`结果是0

```c
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

int test()
{
            
            
	return 12;//函数的返回值
}
int main()
{
            
            
	test();
	printf("程序执行到了这里\n");
	return 0;
}
```

![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F2021031509400984.png%3Fx-oss-process%3Dimage%2Fwatermark%2Ctype_ZmFuZ3poZW5naGVpdGk%2Cshadow_10%2Ctext_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM5MTgzMDM0%2Csize_16%2Ccolor_FFFFFF%2Ct_70&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)  
**其实执行了`return n`就等同于执行了`exit(n)`，因为调用main函数会将main的返回值当作`exit`的参数**

### B：异常退出

按下`Ctrl+C`，其实就是我们发现了程序异常（比如死循环，卡死），然后让操作系统发信号给进程让其终止的过程

### C：\_exit\(\)函数

下面这段代码，我们之前说过没有立即输出文字的原因就是缓冲区没有被刷新

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
            
            

  printf("程序应该执行到这里");
  sleep(3);
  exit(123);

}

```

![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210315095606860.gif&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)  
需要注意的上面的代码我使用了`exit()`函数进行退出，现在我将其换成`_exit()`函数  
![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210315095829424.gif&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)  
**所以`exit()`和`_exit(）`就立竿见影了，`exit()`最后调用的其实也是`_exit()`，只不过它在调用`_exit()`之前，还做了一些其他操作，比如说就有刷新缓冲区**

![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210315100053240.png%3Fx-oss-process%3Dimage%2Fwatermark%2Ctype_ZmFuZ3poZW5naGVpdGk%2Cshadow_10%2Ctext_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM5MTgzMDM0%2Csize_16%2Ccolor_FFFFFF%2Ct_70&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)

## （3）实践

所以到这里就可以使用exit退出进程了，**对于父子进程来说，谁调用谁退出**  
如下程序，对于子进程来说，首先遇到缓冲区不能刷新，但是在3s后使用exit（）强制刷新，表明此时子进程退出了，但是父进程仍然被卡在缓冲区内

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
            
            
  pid_t id=fork();
  if(id==0)
  {
            
            
    while(1)
    {
            
            
       printf("Child running now!");
       sleep(3);
       exit(0);
    }   
  }
  else 
  {
            
            
    while(1)
    {
            
            
      printf("Father running now");
      sleep(1);
    }    
  }
}

```

![在这里插入图片描述](https://ziquyun.com/main/csdn/img?url=https%3A%2F%2Fimg-blog.csdnimg.cn%2F20210315104750479.gif&rfUrl=https%3A%2F%2Fzhangxing-tech.blog.csdn.net%2Farticle%2Fdetails%2F116189390)

- 根据图片及前面讲过的僵尸进程，此时足以说明`exit`退出的是子进程